<?php
/**
 * Copyright (C) EC Brands Corporation - All Rights Reserved
 * Contact Licensing@ECInternet.com for use guidelines
 */
declare(strict_types=1);

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';
if (trim($block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $block->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php if ($titleHtml) : ?>
<div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
    <h1 class="page-title"
        <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()) : ?>
            aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
        <?php endif; ?>>
        <?= /* @noEscape */ $titleHtml ?>
    </h1>

    <?php /** @var \ECInternet\CustomerFeatures\ViewModel\CustomerAccountIndex $viewModel */ ?>
    <?php if ($viewModel = $block->getViewModel()) { ?>
        <?php if ($viewModel->shouldShowAdditionalInformation()) { ?>
            <?php $customerNumber = $viewModel->getCurrentCustomerNumber() ?>
            <?php if (!empty($customerNumber)) { ?>
                <h4 class="customer-number">(<?= /* @noEscape */ $customerNumber ?>)</h4>
            <?php } ?>
        <?php } ?>
    <?php } ?>

    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>
